"""Friendly imports for student controllers and simple simulator scripts."""

from racing.game.config import CameraView, GameConfig, HeadToHeadViewerConfig, RacingAudioConfig
from racing.game.recording import (
    HUMAN_GAMEPLAY_SCHEMA_VERSION,
    HumanGameplayRecorder,
    human_gameplay_record,
    robot_command_to_dict,
    robot_sensors_to_dict,
)
from racing.main import build_scene, create_app, create_head_to_head_viewer_app, main
from racing.physics import (
    PhysicsScene,
    RobotVehicle,
    VehiclePhysicsConfig,
    apply_robot_vehicle_command,
    apply_vehicle_command,
    wheel_connection_points,
)
from racing.race.head_to_head import (
    HeadToHeadRaceEntry,
    HeadToHeadRaceResult,
    HeadToHeadResult,
    HeadToHeadTeamRaceStats,
    classify_head_to_head_winner,
    format_head_to_head_result,
    run_headless_head_to_head,
)
from racing.race.progress import ResolvedTrack, resolve_track
from racing.race.rules import HeadToHeadRaceRules, HeadToHeadScoring
from racing.student.api import (
    CameraCompetitorReading,
    CameraSensors,
    ContactSensors,
    ImuSensors,
    LidarSensors,
    OdometrySensors,
    RobotCommand,
    RobotController,
    RobotControllerFactory,
    RobotSensors,
    StudentControllerSubmission,
    clamp_command,
    default_student_controller,
    load_student_controller,
    load_student_submission,
)
from racing.track.procedural import (
    DEFAULT_PROCEDURAL_TRACK_CONFIG,
    TRACK_ID_PROCEDURAL,
    ProceduralTrackConfig,
    generate_procedural_track,
)
from racing.track.world import (
    MUGELLO_SHORT_LAYOUT,
    NOMINAL_CAR_WIDTH,
    START_POSITION,
    TRACK_ID_MUGELLO_SHORT,
    TRACK_LAYOUT_SCALE,
    TRACK_SCALE,
    TRACK_WIDTH,
    TrackBounds,
    TrackLayout,
    TrackPoint,
    TrackSegment,
    closed_track_points,
    total_track_length,
    track_bounds,
    track_layout_by_id,
    track_layout_ids,
    track_segments,
)

__all__ = [
    "DEFAULT_PROCEDURAL_TRACK_CONFIG",
    "HUMAN_GAMEPLAY_SCHEMA_VERSION",
    "MUGELLO_SHORT_LAYOUT",
    "NOMINAL_CAR_WIDTH",
    "START_POSITION",
    "TRACK_ID_MUGELLO_SHORT",
    "TRACK_ID_PROCEDURAL",
    "TRACK_LAYOUT_SCALE",
    "TRACK_SCALE",
    "TRACK_WIDTH",
    "CameraCompetitorReading",
    "CameraSensors",
    "CameraView",
    "ContactSensors",
    "GameConfig",
    "HeadToHeadRaceEntry",
    "HeadToHeadRaceResult",
    "HeadToHeadRaceRules",
    "HeadToHeadResult",
    "HeadToHeadScoring",
    "HeadToHeadTeamRaceStats",
    "HeadToHeadViewerConfig",
    "HumanGameplayRecorder",
    "ImuSensors",
    "LidarSensors",
    "OdometrySensors",
    "PhysicsScene",
    "ProceduralTrackConfig",
    "RacingAudioConfig",
    "ResolvedTrack",
    "RobotCommand",
    "RobotController",
    "RobotControllerFactory",
    "RobotSensors",
    "RobotVehicle",
    "StudentControllerSubmission",
    "TrackBounds",
    "TrackLayout",
    "TrackPoint",
    "TrackSegment",
    "VehiclePhysicsConfig",
    "apply_robot_vehicle_command",
    "apply_vehicle_command",
    "build_scene",
    "clamp_command",
    "classify_head_to_head_winner",
    "closed_track_points",
    "create_app",
    "create_head_to_head_viewer_app",
    "default_student_controller",
    "format_head_to_head_result",
    "generate_procedural_track",
    "human_gameplay_record",
    "load_student_controller",
    "load_student_submission",
    "main",
    "resolve_track",
    "robot_command_to_dict",
    "robot_sensors_to_dict",
    "run_headless_head_to_head",
    "total_track_length",
    "track_bounds",
    "track_layout_by_id",
    "track_layout_ids",
    "track_segments",
    "wheel_connection_points",
]
