"""Small public entry point for running and scripting the racing simulator."""

from __future__ import annotations

from racing.game.app import (
    build_head_to_head_viewer_scene,
    build_scene,
    create_app,
    create_car_showcase_app,
    create_head_to_head_viewer_app,
    damage_hud_fill_color,
    damage_hud_layout,
)
from racing.game.config import (
    CameraView,
    CarShowcaseConfig,
    CarShowcaseView,
    GameConfig,
    HeadToHeadViewerConfig,
    RacingAudioConfig,
    RunnableApp,
    WindowConfigLike,
    WindowLike,
    configure_window,
    fps_text_for_delta,
    parse_color_rgba,
)
from racing.graphics.camera import (
    CameraRig,
    TrackCameraFrame,
    next_camera_view,
    orthographic_fov_for_viewport,
    projected_track_size,
    top_down_camera_heading_for_viewport,
    update_camera_cycle,
)
from racing.game.cli import build_argument_parser, main
from racing.student.api import StudentControllerSubmission, load_student_controller, load_student_submission
from racing.controls.keyboard import gamepad_command, keyboard_command, manual_drive_command
from racing.graphics.render_assets import SceneAssets
from racing.graphics.track_mesh import (
    wall_collision_offsets_for_side,
    wall_collision_segment_pose,
    wall_collision_segments_for_side,
    wall_collision_thickness,
    wall_inner_segments_for_side,
    wall_offsets_for_side,
)
from racing.graphics.track_rendering import (
    NIGHT_SKY_COLOR,
    START_HEADING_DEGREES,
    TRACK_CURB_WIDTH,
    TRACK_EDGE_BUFFER,
    TRACK_KERB_BASE_Y,
    TRACK_KERB_LOW_HEIGHT,
    TRACK_KERB_RIDGE_HEIGHT,
    TRACK_KERB_SLAB_LENGTH,
    TRACK_LIGHT_SAMPLE_SPACING,
    TRACK_SURFACE_Y,
    TRACK_WALL_BASE_Y,
    TRACK_WALL_COLLISION_EXTRA_THICKNESS,
    TRACK_WALL_COLLISION_OVERLAP,
    TRACK_WALL_COLLISION_THICKNESS,
    TRACK_WALL_HEIGHT,
    TRACK_WALL_THICKNESS,
    TRACK_WARM_LIGHT_COLOR,
    WORLD_FLOOR_COLLISION_CENTER_Y,
    WORLD_FLOOR_COLLISION_HALF_HEIGHT,
    track_light_sample_indices,
    trackside_scenery_positions,
)
from racing.graphics.vehicle_visuals import (
    WHEEL_VISUAL_AXLE_ROTATION_Z_DEGREES,
    RobotVisualRig,
    vehicle_visual_scale,
    wheel_visual_diameter,
)
from racing.graphics.colors import (
    DEFAULT_CHALLENGER_TEAM_COLOR,
    DEFAULT_FORMULA_TEAM_COLOR,
    DEFAULT_INCUMBENT_TEAM_COLOR,
    FORMULA_TEAM_RED,
    UNC_BOLIN_CREEK,
    UNC_CAROLINA_BLUE,
    UNC_CORNERSTONE,
    UNC_FORDHAM_FOUNTAIN,
)

__all__ = [
    "DEFAULT_CHALLENGER_TEAM_COLOR",
    "DEFAULT_FORMULA_TEAM_COLOR",
    "DEFAULT_INCUMBENT_TEAM_COLOR",
    "FORMULA_TEAM_RED",
    "NIGHT_SKY_COLOR",
    "START_HEADING_DEGREES",
    "TRACK_CURB_WIDTH",
    "TRACK_EDGE_BUFFER",
    "TRACK_KERB_BASE_Y",
    "TRACK_KERB_LOW_HEIGHT",
    "TRACK_KERB_RIDGE_HEIGHT",
    "TRACK_KERB_SLAB_LENGTH",
    "TRACK_LIGHT_SAMPLE_SPACING",
    "TRACK_SURFACE_Y",
    "TRACK_WALL_BASE_Y",
    "TRACK_WALL_COLLISION_EXTRA_THICKNESS",
    "TRACK_WALL_COLLISION_OVERLAP",
    "TRACK_WALL_COLLISION_THICKNESS",
    "TRACK_WALL_HEIGHT",
    "TRACK_WALL_THICKNESS",
    "TRACK_WARM_LIGHT_COLOR",
    "UNC_BOLIN_CREEK",
    "UNC_CAROLINA_BLUE",
    "UNC_CORNERSTONE",
    "UNC_FORDHAM_FOUNTAIN",
    "WHEEL_VISUAL_AXLE_ROTATION_Z_DEGREES",
    "WORLD_FLOOR_COLLISION_CENTER_Y",
    "WORLD_FLOOR_COLLISION_HALF_HEIGHT",
    "CameraRig",
    "CameraView",
    "CarShowcaseConfig",
    "CarShowcaseView",
    "GameConfig",
    "HeadToHeadViewerConfig",
    "RacingAudioConfig",
    "RobotVisualRig",
    "RunnableApp",
    "SceneAssets",
    "StudentControllerSubmission",
    "TrackCameraFrame",
    "WindowConfigLike",
    "WindowLike",
    "build_argument_parser",
    "build_head_to_head_viewer_scene",
    "build_scene",
    "configure_window",
    "create_app",
    "create_car_showcase_app",
    "create_head_to_head_viewer_app",
    "damage_hud_fill_color",
    "damage_hud_layout",
    "fps_text_for_delta",
    "gamepad_command",
    "keyboard_command",
    "load_student_controller",
    "load_student_submission",
    "main",
    "manual_drive_command",
    "next_camera_view",
    "orthographic_fov_for_viewport",
    "parse_color_rgba",
    "projected_track_size",
    "top_down_camera_heading_for_viewport",
    "track_light_sample_indices",
    "trackside_scenery_positions",
    "update_camera_cycle",
    "vehicle_visual_scale",
    "wall_collision_offsets_for_side",
    "wall_collision_segment_pose",
    "wall_collision_segments_for_side",
    "wall_collision_thickness",
    "wall_inner_segments_for_side",
    "wall_offsets_for_side",
    "wheel_visual_diameter",
]
